app:
  log:
    filename: log/app.log
    verbosity: \Monolog\Logger::DEBUG
  notification:
    sms-notification:
      recipients: ['774877060']
      credentials:
        uri: /blah
        username: neno
        password: none
    email-notification:
      recipients: ['jan@galvani.cz']
      parameters:
        sender: 'notification@galvani.cz'
        subject: 'Phone number change at NewLogic.cz'

  wkhtmltopdf:
      binary: bin/wkhtmltopdf-amd64 # https://code.google.com/p/wkhtmltopdf/
  newLogicUrl: http://www.newlogic.cz
  redis:
    host: localhost
    prefix: 'newlogic:'